[package]
name = "vow_protocol"
version = "0.1.0"
description = "Glue Vow Protocol - commitment verification on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "vow_protocol"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
solana-program = "1.17.0"
digest = "=0.10.7"
sha2 = "=0.10.9"
