[features]
seeds = false
skip-lint = false

[programs.localnet]
vow_protocol = "CaHLEeQbAqfPXa7ddQ3s8ssF8yc7EYKhwXaibLom6ERN"

[programs.devnet]
vow_protocol = "CaHLEeQbAqfPXa7ddQ3s8ssF8yc7EYKhwXaibLom6ERN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"
