[features]
seeds = true
skip-lint = false

[programs.localnet]
vow_protocol = "592x9qBjrwDiZiVfAuaAqqghnYJvygQFsXLBp5Yqxt3R"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"
